# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy ASP.Net Core app to Azure Web App - moreFairStats

on: workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build MoreFairStats/MoreFairStats.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moreFairStats'
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C77EC738FC904E5DA1BF49675B6B2D4A }}
