
name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-dotnet@v4.3.0

      - run: dotnet publish MoreFairStats/MoreFairStats.csproj -c Release -o /myapp

      - uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: 'morefairstats2'
          publish-profile: ${{secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
          package: /myapp
          clean: true
          restart: true
