
name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4

      - name: dotnet publish
        run: dotnet publish MoreFairStats/MoreFairStats.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'morefairstats2'
          publish-profile: ${{secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
          package: ${{env.DOTNET_ROOT}}/myapp
