name: Build and deploy to Azure Web App

on: workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.404'

      - name: Publish application
        run: dotnet publish MoreFairStats/MoreFairStats.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: Deploy to Azure Web App
        uses: joharasmus/webapps-deploy@v2
        with:
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
